package Shapes.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCanvas = createDescriptorForCanvas();
  /*package*/ final ConceptDescriptor myConceptCircle = createDescriptorForCircle();
  /*package*/ final ConceptDescriptor myConceptColor = createDescriptorForColor();
  /*package*/ final ConceptDescriptor myConceptColorReference = createDescriptorForColorReference();
  /*package*/ final ConceptDescriptor myConceptShape = createDescriptorForShape();
  /*package*/ final ConceptDescriptor myConceptSquare = createDescriptorForSquare();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.extendedLanguage(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, "jetbrains.mps.execution.util");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCanvas, myConceptCircle, myConceptColor, myConceptColorReference, myConceptShape, myConceptSquare);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Canvas:
        return myConceptCanvas;
      case LanguageConceptSwitch.Circle:
        return myConceptCircle;
      case LanguageConceptSwitch.Color:
        return myConceptColor;
      case LanguageConceptSwitch.ColorReference:
        return myConceptColorReference;
      case LanguageConceptSwitch.Shape:
        return myConceptShape;
      case LanguageConceptSwitch.Square:
        return myConceptSquare;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCanvas() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Canvas", 0x1888903ebd8748e8L, 0x9dea8ea8c4506ac4L, 0x519fcbadc6072cd2L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L);
    b.origin("r:17cfc445-42f8-4bcf-a1ad-5ae071da3aa0(Shapes.structure)/5881643585581296850");
    b.version(3);
    b.aggregate("shapes", 0x519fcbadc6072cd4L).target(0x1888903ebd8748e8L, 0x9dea8ea8c4506ac4L, 0x519fcbadc6072cc5L).optional(true).ordered(true).multiple(true).origin("5881643585581296852").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCircle() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Circle", 0x1888903ebd8748e8L, 0x9dea8ea8c4506ac4L, 0x519fcbadc6072cc8L);
    b.class_(false, false, false);
    // extends: Shapes.structure.Shape
    b.super_(0x1888903ebd8748e8L, 0x9dea8ea8c4506ac4L, 0x519fcbadc6072cc5L);
    b.origin("r:17cfc445-42f8-4bcf-a1ad-5ae071da3aa0(Shapes.structure)/5881643585581296840");
    b.version(3);
    b.property("x", 0x519fcbadc6072ccaL).type(PrimitiveTypeId.INTEGER).origin("5881643585581296842").done();
    b.property("y", 0x519fcbadc6072ccbL).type(PrimitiveTypeId.INTEGER).origin("5881643585581296843").done();
    b.property("radius", 0x519fcbadc6072cccL).type(PrimitiveTypeId.INTEGER).origin("5881643585581296844").done();
    b.alias("circle");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForColor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Color", 0x1888903ebd8748e8L, 0x9dea8ea8c4506ac4L, 0x519fcbadc6083c93L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:17cfc445-42f8-4bcf-a1ad-5ae071da3aa0(Shapes.structure)/5881643585581366419");
    b.version(3);
    b.alias("color");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForColorReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "ColorReference", 0x1888903ebd8748e8L, 0x9dea8ea8c4506ac4L, 0x519fcbadc60a24b6L);
    b.class_(false, false, false);
    b.origin("r:17cfc445-42f8-4bcf-a1ad-5ae071da3aa0(Shapes.structure)/5881643585581491382");
    b.version(3);
    b.associate("tarjet", 0x519fcbadc60a24b7L).target(0x1888903ebd8748e8L, 0x9dea8ea8c4506ac4L, 0x519fcbadc6083c93L).optional(false).origin("5881643585581491383").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForShape() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Shape", 0x1888903ebd8748e8L, 0x9dea8ea8c4506ac4L, 0x519fcbadc6072cc5L);
    b.class_(false, true, false);
    b.origin("r:17cfc445-42f8-4bcf-a1ad-5ae071da3aa0(Shapes.structure)/5881643585581296837");
    b.version(3);
    b.aggregate("color", 0x519fcbadc60afc36L).target(0x1888903ebd8748e8L, 0x9dea8ea8c4506ac4L, 0x519fcbadc60a24b6L).optional(false).ordered(true).multiple(false).origin("5881643585581546550").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSquare() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Square", 0x1888903ebd8748e8L, 0x9dea8ea8c4506ac4L, 0x519fcbadc6072cceL);
    b.class_(false, false, false);
    // extends: Shapes.structure.Shape
    b.super_(0x1888903ebd8748e8L, 0x9dea8ea8c4506ac4L, 0x519fcbadc6072cc5L);
    b.origin("r:17cfc445-42f8-4bcf-a1ad-5ae071da3aa0(Shapes.structure)/5881643585581296846");
    b.version(3);
    b.property("upperLeftX", 0x519fcbadc6072ccfL).type(PrimitiveTypeId.INTEGER).origin("5881643585581296847").done();
    b.property("upperLeftY", 0x519fcbadc6072cd0L).type(PrimitiveTypeId.INTEGER).origin("5881643585581296848").done();
    b.property("size", 0x519fcbadc6072cd1L).type(PrimitiveTypeId.INTEGER).origin("5881643585581296849").done();
    b.alias("square");
    return b.create();
  }
}
